version: "3"

services:

  mysql-server:
    image: mysql:latest
    restart: "always"
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "3307:3306"
    environment:
        MYSQL_USER: default
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: altschool
        JWT_SECRET: nasdjioi3oubwek
    container_name: mysql-server
    volumes:
      - ./db_data/mysql:/var/lib/mysql

  school-sms:
    build:
      context: .
    restart: "unless-stopped"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - mysql-server
    container_name: school-sms
    ports:
      - "8080:80"